name: Repository Health Check

on:
  schedule:
    # Run every night at midnight
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  health-check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install @actions/core @actions/github axios

      - name: Run health check
        run: |
          cd packages/health-check
          node index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload health check report
        uses: actions/upload-artifact@v3
        with:
          name: health-check-report
          path: health-check-report.md
          
      - name: Add job summary
        run: cat health-check-report.md >> $GITHUB_STEP_SUMMARY

      - name: Commit report to repository
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add health-check-report.md
          git commit -m "Update health check report" || echo "No changes to commit"
          git push
        env:
          # Need a token with write permissions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}